### ISSUE TITLE
Error in module Node.Thunk Unknown type 'Error'

### ISSUE THREAD

**Issue by adamwong246** [andreypopp/purescript-node-thunk#2] opened 2015-01-18 23:53 UTC
my code
```
module Chapter2 where

import Node.Thunk

foreign import fs "var fs = require('fs');" :: {
  readFile :: ThunkFn1 String String
  }

readFile = runThunkFn1 fs.readFile

main = readFile "README.md"
```
I'm not the only one with this issue
http://ircbrowse.net/browse/purescript?id=1900&timestamp=1413878622#t1413878622

**Comment by epost** [comment] 2015-01-29 13:40
Breakage is caused by the removal of ```Error``` from purescript-globals: https://github.com/purescript/purescript-globals/commit/0a6cca15f04dfa7951165ffcf4ec2bc62d854bf9, so if we wanted to fix this a bit more comprehensively, maybe it would make sense to switch purescript-node-thunk over to ```(Error a)``` from [purescript-transformers](https://github.com/purescript/purescript-transformers/blob/9e1c4a0bf07ce6cd7db7318362ab75bb5508c314/src/Control/Monad/Error.purs)?

**Comment by epost** [comment] 2015-01-31 15:18
Fixed in https://github.com/andreypopp/purescript-node-thunk/commit/a434f6099b964486d4483fd8ce60fb7c9186b9b0. @eamelink

**Closed by epost** 2015-01-31 15:18 UTC
